DROP TABLE restaurant_order IF EXISTS;
DROP TABLE user_role IF EXISTS;
DROP TABLE menu_meal IF EXISTS;
DROP TABLE role IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE meal IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP TABLE users IF EXISTS;

DROP SEQUENCE IF EXISTS PUBLIC.global_seq;

CREATE SEQUENCE PUBLIC.global_seq AS INTEGER START WITH 100000;

CREATE TABLE PUBLIC.restaurant
(
    name VARCHAR(255) NOT NULL,
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE PUBLIC.GLOBAL_SEQ PRIMARY KEY
);

INSERT INTO PUBLIC.RESTAURANT (NAME)
VALUES ('Mirazur'),
       ('Gaggan');

CREATE TABLE PUBLIC.users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE PUBLIC.GLOBAL_SEQ PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);

INSERT INTO PUBLIC.USERS (name, email, password)
VALUES ('Admin', 'admin@gmail.com', '$2a$10$IqTJTjn39IU5.7sSCDQxzu3xug6z/LPU6IF0azE/8CkHCwYEnwBX.'),
       ('Oleg', 'oleg@mail.ru', '$2a$10$Tl7q5gHahZGbb.GEr5Zr9u./qM1U./EQOHr3wkop3c4pG43S55rRq'),
       ('orderUser','orderUser@mail.ru','password'),
       ('excUser','excUser@mail.ru','password');

CREATE TABLE PUBLIC.role
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE PUBLIC.GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO PUBLIC.ROLE(name)
VALUES ('ADMIN'),
       ('USER');

CREATE TABLE PUBLIC.user_role
(
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);

INSERT INTO PUBLIC.USER_ROLE (USER_ID, ROLE_ID)
VALUES (100002, 100006), (100003, 100006), (100004,100007);

CREATE TABLE PUBLIC.menu
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant_id INTEGER                 NOT NULL,
    created       TIMESTAMP DEFAULT now() NOT NULL,
    is_enabled    BOOLEAN   DEFAULT true,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

INSERT INTO PUBLIC.MENU(restaurant_id, is_enabled)
VALUES (100000, true),
       (100001, true);

CREATE TABLE PUBLIC.meal
(
    name          VARCHAR(255) NOT NULL,
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE PUBLIC.GLOBAL_SEQ PRIMARY KEY,
    restaraunt_id INTEGER      NOT NULL,
    meal_type     VARCHAR(255) DEFAULT 'Not In Menu',
    price         INTEGER      NOT NULL,
    FOREIGN KEY (restaraunt_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

INSERT INTO PUBLIC.MEAL(NAME, restaraunt_id, price)
VALUES ('Grand Velas Tacos', 100000, 25000),
       ('Fortress Stilt Fisherman Indulgence', 100000, 2060),
       ('Beluga''s Almas caviar', 100000, 7899),
       ('FleurBurger', 100000, 5466),
       ('Billion Dollar Popcorn', 100000, 2800),
       ('GOLDEN OPULENCE SUNDAE', 100001, 1000),
       ('THE ZILLION DOLLAR LOBSTER FRITTATA', 100001, 2000),
       ('WHITE TRUFFLE AND GOLD PIZZA', 100001, 2800);

CREATE TABLE PUBLIC.restaurant_order
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE PUBLIC.GLOBAL_SEQ PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    restaurant_id INTEGER NOT NULL,
    CONSTRAINT user_restaurant_idx UNIQUE (user_id, restaurant_id, created),
    created       TIMESTAMP DEFAULT now(),
    is_enabled    BOOLEAN   DEFAULT false,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

INSERT INTO PUBLIC.restaurant_order(user_id, restaurant_id, created, is_enabled)
VALUES (100004,100001, TO_DATE('25/01/2022 10:30:40', 'DD/MM/YYYY HH:MI:SS'), false),
       (100005,100000, TO_DATE('25/01/2022 10:30:40', 'DD/MM/YYYY HH:MI:SS'), true);
