DELETE FROM USERS;
DELETE FROM ROLES;
DELETE FROM USERS_ROLES;
DELETE FROM RESTAURANTS;
DELETE FROM MEALS;
DELETE FROM ORDERS;
DELETE FROM RESTAURANTS_ORDERS;
DELETE FROM ORDER_MEAL;

INSERT INTO USERS (name, email, password)
VALUES ('Admin', 'admin@gmail.com', '$2a$10$IqTJTjn39IU5.7sSCDQxzu3xug6z/LPU6IF0azE/8CkHCwYEnwBX.');
       ('Oleg', 'test@email.com', '$2a$10$Tl7q5gHahZGbb.GEr5Zr9u./qM1U./EQOHr3wkop3c4pG43S55rRq');

INSERT INTO ROLES(name)
VALUE ('ADMIN');
VALUE ('USER');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID)
VALUES ('100001', '100003');
VALUES ('100002', '100004');

INSERT INTO RESTAURANTS (NAME)
VALUE ('Тануки');
VALUE ('Макдональдс');